AWSTemplateFormatVersion: '2010-09-09'
Description: 'Initial deployment for Video Converter Lambda - ECR Repository only'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

Resources:
  # ECRリポジトリ
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${AWS::StackName}-video-converter'
      ImageScanningConfiguration:
        ScanOnPush: true

Outputs:
  ECRRepositoryUri:
    Description: ECR repository URI
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}'
    Export:
      Name: !Sub '${AWS::StackName}-ecr-uri'